### ISSUE TITLE
there's no setCredentials method!

### ISSUE THREAD

**Issue by imalitavakoli** [apility/nets-easy-php#2]
Hi,

Thanks for the library, I liked to start using it... But I get the following error:
```
Fatal error: Uncaught Error: Call to undefined method NETS\Easy::setCredentials() in D:\projects\localhost-tests\index.php on line 8
```

In your readme file you said set our credintials like so:
```
Easy::setCredentials([
  'secret_key' => '00000000000000000000000000000000',
  'checkout_key' => '00000000000000000000000000000000',
  'merchant_id' => '000000000'
]);
```

But it seems that there's no such method!

Am I doing something wrong?
And is this library can be used standalone or should be in a Laravel project?

Thanks a lot,
Ali

**Comment by thomas-alrek** [comment]
Hi. There was a typo in the documentation. Please use `Easy::setup([...])` instead.
Fixed in ca0ca7a59dd6d1a58baa05749a7b6fa06c461c72.

This library is written to be used standalone, but it utilizes a few helpers from Laravel's `illuminate/support` package.
